import { PERMISSION_TYPE_ENUM } from '@/common/enums'
import test from './test'
import catalog from './catalog'
import nest from './nest'

export default [
  {
    label: '演示模块',
    value: 213,
    icon: 'visits',
    permission: 'catalog:demoModule',
    show: true,
    type: PERMISSION_TYPE_ENUM.CATALOG,
    children: [
      ...test,
      ...catalog,
      ...nest,
    ]
  },
]





const arr = [
  {
    value: 175,
    label: '微信管理',
    icon: 'mobile',
    permission: 'catalog:applet',
    keepalive: false,
    tab: false,
    multiple: false,
    show: true,
    type: 0,
    url: null,
    componentName: null,
    sort: 6,
    parentId: 0,
    status: 1,
    children: [
      {
        value: 176,
        label: '小程序',
        icon: null,
        permission: 'wechatApplet:page',
        keepalive: false,
        tab: true,
        multiple: false,
        show: true,
        type: 1,
        url: '/wechat/applet/index',
        componentName: null,
        sort: 1,
        parentId: 175,
        status: 1,
        route: {
          path: '/wechat/applet',
          name: 'wechat-applet',
          redirect: null,
          component: '/wechat/applet/index',
        },
        _level: 2,
        children: [
          {
            value: 177,
            label: '查看',
            icon: null,
            permission: 'wechatApplet:info',
            keepalive: false,
            tab: false,
            multiple: false,
            show: true,
            type: 2,
            url: null,
            componentName: null,
            sort: 1,
            parentId: 176,
            status: 1,
            _level: 3,
          },
          {
            value: 178,
            label: '新增',
            icon: null,
            permission: 'wechatApplet:create',
            keepalive: false,
            tab: false,
            multiple: false,
            show: true,
            type: 2,
            url: null,
            componentName: null,
            sort: 1,
            parentId: 176,
            status: 1,
            _level: 3,
          },
          {
            value: 179,
            label: '编辑',
            icon: null,
            permission: 'wechatApplet:update,wechatApplet:info',
            keepalive: false,
            tab: false,
            multiple: false,
            show: true,
            type: 2,
            url: null,
            componentName: null,
            sort: 1,
            parentId: 176,
            status: 1,
            _level: 3,
          },
          {
            value: 180,
            label: '删除',
            icon: null,
            permission: 'wechatApplet:delete',
            keepalive: false,
            tab: false,
            multiple: false,
            show: true,
            type: 2,
            url: null,
            componentName: null,
            sort: 1,
            parentId: 176,
            status: 1,
            _level: 3,
          },
          {
            value: 181,
            label: '导出',
            icon: null,
            permission: 'wechatApplet:export',
            keepalive: false,
            tab: false,
            multiple: false,
            show: true,
            type: 2,
            url: null,
            componentName: null,
            sort: 1,
            parentId: 176,
            status: 1,
            _level: 3,
          },
          {
            value: 182,
            label: '生成二维码',
            icon: null,
            permission: 'wechatApplet:qrcode',
            keepalive: false,
            tab: false,
            multiple: false,
            show: true,
            type: 2,
            url: null,
            componentName: null,
            sort: 1,
            parentId: 176,
            status: 1,
            _level: 3,
          },
        ],
      },
    ],
    _level: 1,
  },
  {
    value: 15,
    label: '基础设施',
    icon: 'folder',
    permission: 'catalog:installation',
    keepalive: false,
    tab: false,
    multiple: false,
    show: true,
    type: 0,
    url: null,
    componentName: null,
    sort: 3,
    parentId: 0,
    status: 1,
    children: [
      {
        value: 2,
        label: '开发配置',
        icon: 'development',
        permission: 'catalog:develop',
        keepalive: false,
        tab: false,
        multiple: false,
        show: true,
        type: 0,
        url: null,
        componentName: null,
        sort: 6,
        parentId: 15,
        status: 1,
        children: [
          {
            value: 79,
            label: '消息通知',
            icon: 'database',
            permission: 'catalog:notice',
            keepalive: false,
            tab: false,
            multiple: false,
            show: true,
            type: 0,
            url: null,
            componentName: null,
            sort: 3,
            parentId: 2,
            status: 1,
            _level: 3,
            children: [
              {
                value: 80,
                label: '通知模版',
                icon: 'login-log',
                permission: 'noticeTemplate:page',
                keepalive: false,
                tab: true,
                multiple: false,
                show: true,
                type: 1,
                url: '/infrastructure/develop/notice/template/index',
                componentName: null,
                sort: 1,
                parentId: 79,
                status: 1,
                route: {
                  path: '/infrastructure/develop/notice/template',
                  name: 'infrastructure-develop-notice-template',
                  redirect: null,
                  component: '/infrastructure/develop/notice/template/index',
                },
                _level: 4,
                children: [
                  {
                    value: 81,
                    label: '查看',
                    icon: null,
                    permission: 'noticeTemplate:info',
                    keepalive: false,
                    tab: false,
                    multiple: false,
                    show: true,
                    type: 2,
                    url: null,
                    componentName: null,
                    sort: 1,
                    parentId: 80,
                    status: 1,
                    _level: 5,
                  },
                  {
                    value: 82,
                    label: '新增',
                    icon: null,
                    permission: 'noticeTemplate:create',
                    keepalive: false,
                    tab: false,
                    multiple: false,
                    show: true,
                    type: 2,
                    url: null,
                    componentName: null,
                    sort: 1,
                    parentId: 80,
                    status: 1,
                    _level: 5,
                  },
                  {
                    value: 83,
                    label: '编辑',
                    icon: null,
                    permission: 'noticeTemplate:update,noticeTemplate:info',
                    keepalive: false,
                    tab: false,
                    multiple: false,
                    show: true,
                    type: 2,
                    url: null,
                    componentName: null,
                    sort: 1,
                    parentId: 80,
                    status: 1,
                    _level: 5,
                  },
                  {
                    value: 84,
                    label: '删除',
                    icon: null,
                    permission: 'noticeTemplate:delete',
                    keepalive: false,
                    tab: false,
                    multiple: false,
                    show: true,
                    type: 2,
                    url: null,
                    componentName: null,
                    sort: 1,
                    parentId: 80,
                    status: 1,
                    _level: 5,
                  },
                  {
                    value: 85,
                    label: '设置是否禁用',
                    icon: null,
                    permission: 'noticeTemplate:status',
                    keepalive: false,
                    tab: false,
                    multiple: false,
                    show: true,
                    type: 2,
                    url: null,
                    componentName: null,
                    sort: 1,
                    parentId: 80,
                    status: 1,
                    _level: 5,
                  },
                  {
                    value: 138,
                    label: '导出',
                    icon: null,
                    permission: 'noticeTemplate:export',
                    keepalive: false,
                    tab: false,
                    multiple: false,
                    show: true,
                    type: 2,
                    url: null,
                    componentName: null,
                    sort: 1,
                    parentId: 80,
                    status: 1,
                    _level: 5,
                  },
                ],
              },
              {
                value: 86,
                label: '通知记录',
                icon: 'database',
                permission: 'notice:page,tenant:selectPage',
                keepalive: false,
                tab: true,
                multiple: false,
                show: true,
                type: 1,
                url: '/infrastructure/develop/notice/list/index',
                componentName: null,
                sort: 1,
                parentId: 79,
                status: 1,
                route: {
                  path: '/infrastructure/develop/notice/list',
                  name: 'infrastructure-develop-notice-list',
                  redirect: null,
                  component: '/infrastructure/develop/notice/list/index',
                },
                _level: 4,
                children: [
                  {
                    value: 87,
                    label: '查看',
                    icon: null,
                    permission: 'notice:info',
                    keepalive: false,
                    tab: false,
                    multiple: false,
                    show: true,
                    type: 2,
                    url: null,
                    componentName: null,
                    sort: 1,
                    parentId: 86,
                    status: 1,
                    _level: 5,
                  },
                  {
                    value: 88,
                    label: '删除',
                    icon: null,
                    permission: 'notice:delete',
                    keepalive: false,
                    tab: false,
                    multiple: false,
                    show: true,
                    type: 2,
                    url: null,
                    componentName: null,
                    sort: 1,
                    parentId: 86,
                    status: 1,
                    _level: 5,
                  },
                  {
                    value: 89,
                    label: '测试通知',
                    icon: '',
                    permission:
                      'notice:push,noticeTemplate:select,dept:select,adminer:select',
                    keepalive: false,
                    tab: false,
                    multiple: false,
                    show: true,
                    type: 2,
                    url: null,
                    componentName: null,
                    sort: 1,
                    parentId: 86,
                    status: 1,
                    _level: 5,
                  },
                  {
                    value: 139,
                    label: '导出',
                    icon: null,
                    permission: 'notice:export',
                    keepalive: false,
                    tab: false,
                    multiple: false,
                    show: true,
                    type: 2,
                    url: null,
                    componentName: null,
                    sort: 1,
                    parentId: 86,
                    status: 1,
                    _level: 5,
                  },
                ],
              },
            ],
          },
        ],
        _level: 2,
      },
    ],
    _level: 1,
  },
];
